---
# tasks file for mysql


- name: 'Install the mysql package'
  apt:
    name: 'mysql-server={{ mysql_version }}-0ubuntu0.18.04.1'
    state: 'present'
    update_cache: true
  become: true

- name: 'Install python requirements for mysql modules'
  pip:
    name: 'PyMySQL'
    state: 'present'
  become: true

- name: 'Create a non-root mysql user'
  mysql_user:
    name: '{{ mysql_user_name }}'
    password: '{{ mysql_user_password }}'
    update_password: 'on_create'
    priv: '{{ mysql_user_privileges }}'
    login_unix_socket: '{{ mysql_unix_socket_path }}'
    state: 'present'
  become: true

- name: 'Ensure that mysql service is started'
  service:
    name: 'mysql'
    state: 'started'
    enabled: true

